// Copied from plupload
export const FileStatus = {
  QUEUED: 1,
  UPLOADING: 2,
  FAILED: 4,
  DONE: 5,
  RESIZING: 6,
};

// Copied from plupload
export const States = {
  STOPPED: 1,
  STARTED: 2,
};

// Copied from plupload
export const Errors = {
  GENERIC_ERROR: -100,
  HTTP_ERROR: -200,
  IO_ERROR: -300,
  SECURITY_ERROR: -400,
  INIT_ERROR: -500,
  FILE_SIZE_ERROR: -600,
  FILE_EXTENSION_ERROR: -601,
  FILE_DUPLICATE_ERROR: -602,
  IMAGE_FORMAT_ERROR: -700,
  MEMORY_ERROR: -701,
  IMAGE_DIMENSIONS_ERROR: -702,
  OPTION_ERROR: -800,
};

export const ActionTypes = {
  INIT: 'INIT',
  SET_OPTION: 'SET_OPTION',
  REFRESH: 'REFRESH',
  START: 'START',
  STOP: 'STOP',
  DISABLE_BROWSE: 'DISABLE_BROWSE',
  ADD_FILE: 'ADD_FILE',
  REMOVE_FILE: 'REMOVE_FILE',
  DESTROY: 'DESTROY',
  CLEAR: 'CLEAR',

  INITING: 'INITING',
  POST_INIT: 'POST_INIT',
  OPTION_CHANGED: 'OPTION_CHANGED',
  REFRESHING: 'REFRESHING',
  STATE_CHANGED: 'STATE_CHANGED',
  UPLOAD_FILE: 'UPLOAD_FILE',
  BEFORE_UPLOAD: 'BEFORE_UPLOAD',
  QUEUE_CHANGED: 'QUEUE_CHANGED',
  UPLOAD_PROGRESS: 'UPLOAD_PROGRESS',
  FILES_REMOVED: 'FILES_REMOVED',
  FILE_FILTERED: 'FILE_FILTERED',
  FILES_ADDED: 'FILES_ADDED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  CHUNK_UPLOADED: 'CHUNK_UPLOADED',
  UPLOAD_COMPLETE: 'UPLOAD_COMPLETE',
  ERROR: 'ERROR',
  DESTROYING: 'DESTROYING',
};

Object.keys(ActionTypes).forEach(key => { ActionTypes[key] = `redux-plupload/${key}`; });

export const DEFAULT_UPLOADER_HANDLE = 'default';
